# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ALCalculatorDialog
                                 A QGIS plugin
 This plugin calculates a total area or length of features in a vector layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Bartosz Łęczycki
        email                : bartosz.leczycki98@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import *
from qgis.utils import *
from qgis.core import *
from PyQt5.QtCore import *
from qgis.PyQt.QtGui import *
from PyQt5.QtWidgets import *


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ALCalculator_dialog_base.ui'))


class ALCalculatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ALCalculatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect


        self.setupUi(self)
        
        self.stackedWidget.setCurrentWidget(self.home)

        self.pbAreaPage.clicked.connect(self.gotoArea)
        self.pbLengthPage.clicked.connect(self.gotoLength)
        self.pbJumpArea.clicked.connect(self.gotoArea)
        self.pbJumpLength.clicked.connect(self.gotoLength)


        #precisionValue = self.spLengthPrecision.value()

        self.cbLengthLayerList.setFilters(QgsMapLayerProxyModel.LineLayer)
        self.cbAreaLayerList.setFilters(QgsMapLayerProxyModel.PolygonLayer)

    def gotoArea(self):
        self.stackedWidget.setCurrentWidget(self.area)
        
    def gotoLength(self):
        self.stackedWidget.setCurrentWidget(self.length)


